### ISSUE TITLE
Add support for client results

### ISSUE THREAD

**Issue by maca88** [lepicekmichal/SignalRKore#1]
Hi,

First, big thank you for creating the SignalR client purely in Kotlin with KMM support, really appreciated!

Now to my feature request. It would be greatly appreciated if the library could also support client results introduced in .NET 7:
https://learn.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-7.0#client-results

For reference, the following the PR added support for client results to the official Java client:
https://github.com/dotnet/aspnetcore/pull/41774/files

**Comment by lepicekmichal** [comment]
Added in version 0.7.0
