### ISSUE TITLE
[Bug]: Wrong access token being used when trying to reconnect

### ISSUE THREAD

**Issue by ReneHaddad** [lepicekmichal/SignalRKore#10]
### Description

Thank you for creating a SignalR client in Kotlin with Kotlin multiplatform support, much appreciated 🚀 

We are in the process of migrating from the SignalR Android SDK to `SignalRKore` so we can share logic between Android and iOS and leverage the automatic reconnect built into your solution. We have one problem with the reconnect behavior, the websocket call fails with :
`401 and www-authenticate Bearer error="invalid_token", error_description="The signature key was not found"`

### Scenario

1. Start `HubConnection` to initiate the negotiation call with access token provided to `SignalRKore`
2. Access token from negotiation is received and stored in the headers `MutableMap` via   
``` response.accessToken?.let { token -> headers["Authorization"] = "Bearer $token"}```
3. Code proceeds to do Redirected negotiation call and Web socket call successfully
4. App loses internet connection, `SignalRKore` tries to reconnect and initiates the negotiation call again with the expired access token from step 2

### Expected behavior
when trying to reconnect,`SignalRKore` should use the access token that is passed initially to the SDK to initiate negotiation call again instead of the access token that was saved in the map in step 2 of the scenario.

### Configuration
Version: 0.8.7
Platform: Android 🤖

**Comment by lepicekmichal** [comment]
Thank you for your report. I have published a new version, 0.9.0. 
Please check if it is working for you now.

**Comment by ReneHaddad** [comment]
The issue is fixed now! Thank you 🥇
