### ISSUE TITLE
Any plans for REST Transport Fallback? 

### ISSUE THREAD

**Issue by sebanitu** [lepicekmichal/SignalRKore#9]
Hi there! 

I am really interested in using your library in our under development multi platform app. However, the resulting app also contains an iOS AppClip target which can't use a socket connection as per Apple's design. Is there a chance that we might see support for transport fallback to HTTP REST anytime soon? 

Warm regards, 
Sebastian

**Comment by lepicekmichal** [comment]
Hi, 
sorry for the late reply. I am not too familiar with iOS so please bear with me. 

As per quick search, wouldn't this library work as long as you turn off the websocket transport? There is still **long polling** transport and in the future (when ktor 3 is out) **server sent events** will also be supported.

So if you can easily try, it should just be:
```kotlin
HubConnectionBuilder
    .create(url) {
        transportEnum = TransportEnum.LongPolling
    }
```

**Comment by lepicekmichal** [comment]
I honestly have no idea. I think not much effort should be needed. 
But then again, it is totally different architecture, so there might be some big bump on the road I'm not seeing.
